formatter: "" # this is required

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: |-
  # Azure Resource Group (RG) module

  This module simplifies the creation of one or more resource groups (rg) in Azure. It is designed to be flexible, modular, and easy to use, ensuring a seamless and secure rg deployment experience.

  # Features

  Creates one or more maintenance configurations in Azure with the following (optional) features:

  - Resource groups are created with a standard naming convention: prefix-application-name-environment-001
  - If necessary this can be changed by using the instance object (e.g. instance = "002").

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ## Example(s)

  ### 2 resource groups with a different instance number (e.g lab-identity-net-prod-002, lab-identity-vms-prod-003)

  ```hcl
  {{ include ".examples/example_resource_group.tf"}}
  ```

  # Known issues and limitations

  No known issues or limitations.

  # Author

  Stefan Vonk (vonk.stefan@live.nl) Technical Specialist

output:
  file: ""
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true